[build]
  base = "yudao-ui/yudao-ui-admin-vue3"
  command = "npm i && npm run build:prod"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# （可选）API 代理，按需打开
# [[redirects]]
#   from = "/admin-api/*"
#   to = "http://YOUR-BACKEND:48080/admin-api/:splat"
#   status = 200
#   force = true
